/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algebra;

import java.awt.Color;

/**
 *
 * @author ghaith
 */
public class Operations extends javax.swing.JFrame {

    /**
     * Creates new form Operations
     */
    int x1, y1, x2, y2;
    Object Objects1[][];
    String titles1[];
    Object Objects2[][];
    String titles2[];

    public Operations() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        mul = new javax.swing.JRadioButton();
        min = new javax.swing.JRadioButton();
        plu = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        X1 = new javax.swing.JTextField();
        Y1 = new javax.swing.JTextField();
        X2 = new javax.swing.JTextField();
        Y2 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        err = new javax.swing.JLabel();

        jScrollPane1.setViewportView(table1);

        jScrollPane2.setViewportView(table2);

        buttonGroup1.add(mul);
        mul.setText("*");

        buttonGroup1.add(min);
        min.setText("-");
        min.setToolTipText("");

        buttonGroup1.add(plu);
        plu.setText("+");

        jToggleButton1.setText("=");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(table3);

        X1.setForeground(java.awt.Color.lightGray);
        X1.setText("X");
        X1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                X1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                X1FocusLost(evt);
            }
        });

        Y1.setForeground(java.awt.Color.lightGray);
        Y1.setText("Y");
        Y1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Y1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Y1FocusLost(evt);
            }
        });

        X2.setForeground(java.awt.Color.lightGray);
        X2.setText("X");
        X2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                X2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                X2FocusLost(evt);
            }
        });

        Y2.setForeground(java.awt.Color.lightGray);
        Y2.setText("Y");
        Y2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Y2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Y2FocusLost(evt);
            }
        });

        jToggleButton2.setText("Save");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Save");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        err.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mul)
                            .addComponent(min)
                            .addComponent(plu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(X1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(X2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Y2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jToggleButton2)
                    .addComponent(Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3)
                    .addComponent(X2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plu)
                        .addGap(72, 72, 72)
                        .addComponent(jToggleButton1)
                        .addGap(274, 274, 274)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(err, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(508, 508, 508))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void X1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_X1FocusGained
        if (X1.getText().equals("X")) {
            X1.setForeground(Color.BLACK);
            X1.setText("");
        }
    }//GEN-LAST:event_X1FocusGained

    private void Y1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Y1FocusGained
        if (Y1.getText().equals("Y")) {
            Y1.setForeground(Color.BLACK);
            Y1.setText("");
        }
    }//GEN-LAST:event_Y1FocusGained

    private void X1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_X1FocusLost
        if (X1.getText().equals("")) {
            X1.setForeground(Color.LIGHT_GRAY);
            X1.setText("X");
        }
    }//GEN-LAST:event_X1FocusLost

    private void Y1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Y1FocusLost
        if (Y1.getText().equals("")) {
            Y1.setForeground(Color.LIGHT_GRAY);
            Y1.setText("Y");
        }
    }//GEN-LAST:event_Y1FocusLost

    private void X2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_X2FocusGained
        if (X2.getText().equals("X")) {
            X2.setForeground(Color.BLACK);
            X2.setText("");
        }
    }//GEN-LAST:event_X2FocusGained

    private void X2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_X2FocusLost
        if (X2.getText().equals("")) {
            X2.setForeground(Color.LIGHT_GRAY);
            X2.setText("X");
        }
    }//GEN-LAST:event_X2FocusLost

    private void Y2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Y2FocusGained
        if (Y2.getText().equals("Y")) {
            Y2.setForeground(Color.BLACK);
            Y2.setText("");
        }
    }//GEN-LAST:event_Y2FocusGained

    private void Y2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Y2FocusLost
        if (Y2.getText().equals("")) {
            Y2.setForeground(Color.LIGHT_GRAY);
            Y2.setText("Y");
        }
    }//GEN-LAST:event_Y2FocusLost

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        x1 = Integer.parseInt(X1.getText());
        y1 = Integer.parseInt(Y1.getText());
        titles1 = new String[y1];
        for (int i = 0; i < y1; i++) {
            titles1[i] = "x" + (i+1);
        }
        Objects1 = new Object[x1][y1];
        table1.setModel(new javax.swing.table.DefaultTableModel(Objects1, titles1));
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        x2 = Integer.parseInt(X2.getText());
        y2 = Integer.parseInt(Y2.getText());
        titles2 = new String[y2];
        for (int i = 0; i < y2; i++) {
            titles2[i] = "x" + (i+1);
        }
        Objects2 = new Object[x2][y2];
        table2.setModel(new javax.swing.table.DefaultTableModel(Objects2, titles2));
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        double values1[][] = new double[x1][y1];
        double values2[][] = new double[x2][y2];

        for (int i = 0; i < x1; i++) {
            for (int j = 0; j < y1; j++) {
                if (table1.getValueAt(i, j) == null) {
                    System.out.println("Value = null");
                    return;
                }
                values1[i][j] = Double.parseDouble("" + table1.getValueAt(i, j));
            }
        }

        for (int i = 0; i < x2; i++) {
            for (int j = 0; j < y2; j++) {
                if (table2.getValueAt(i, j) == null) {
                    System.out.println("Value = null");
                    return;
                }
                values2[i][j] = Double.parseDouble("" + table2.getValueAt(i, j));
            }
        }
        double values3[][];
        if (plu.isSelected()) {
            if (x1 != x2 || y1 != y2) {
                err.setText("x1 != x2 or y1 != y2");
                return;
            } else {
                err.setText("");
                values3 = new double[x1][y1];
                for (int i = 0; i < x1; i++) {
                    for (int j = 0; j < y1; j++) {
                        values3[i][j] = values1[i][j] + values2[i][j];
                    }
                }
            }

            Object[][] objects = new Object[x1][y1];
            String titles[] = new String[y1];
            for (int i = 0; i < y1; i++) {
                titles[i] = ""+(i+1);
            }
            for (int i = 0; i < x1; i++) {
                for (int j = 0; j < y1; j++) {
                    objects[i][j] = (Object) values3[i][j];
                }
            }
            table3.setModel(new javax.swing.table.DefaultTableModel(objects, titles));
        } else if (min.isSelected()) {
            if (x1 != x2 || y1 != y2) {
                err.setText("x1 != x2 or y1 != y2");
                return;
            } else {
                err.setText("");
                values3 = new double[x1][y1];
                for (int i = 0; i < x1; i++) {
                    for (int j = 0; j < y1; j++) {
                        values3[i][j] = values1[i][j] - values2[i][j];
                    }
                }
            }

            Object[][] objects = new Object[x1][y1];
            String titles[] = new String[y1];
            for (int i = 0; i < y1; i++) {
                titles[i] = ""+(i+1);
            }
            for (int i = 0; i < x1; i++) {
                for (int j = 0; j < y1; j++) {
                    objects[i][j] = (Object) values3[i][j];
                }
            }
            table3.setModel(new javax.swing.table.DefaultTableModel(objects, titles));
        } 
        else if (mul.isSelected()) {
            if (y1 != x2) {
                err.setText("y1 does not equal x2");
                return;
            } else {
                Object[][] objects = new Object[x2][y1];
                String titles[] = new String[y1];
                for(int i = 0; i < y1; i++){
                    titles[i] = ""+(i+1);                
                }
                values3 = Algebra.multiply(values2, values1);
                for (int i = 0; i < x2; i++) {
                    for (int j = 0; j < y1; j++) {
                        objects[i][j] = (Object) values3[i][j];
                    }
                }
                table3.setModel(new javax.swing.table.DefaultTableModel(objects, titles));
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField X1;
    private javax.swing.JTextField X2;
    private javax.swing.JTextField Y1;
    private javax.swing.JTextField Y2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel err;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JRadioButton min;
    private javax.swing.JRadioButton mul;
    private javax.swing.JRadioButton plu;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    // End of variables declaration//GEN-END:variables
}
